[package]
name = "loom-erofs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
loom-map = { path = "../loom-map" }
loom-view = { path = "../loom-view" }
lz4_flex = { version = "0.14.0", default-features = false, features = ["std", "safe-encode", "safe-decode"] }

[lints]
workspace = true
